on:
  schedule:
    - cron:  0 0 * * 1

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        cfengine: ["lucee@5", "lucee@6", "adobe@2021", "adobe@2023", "adobe@2025", "boxlang@1", "boxlang-cfml@1"]
        experimental: [ false ]
        coldbox: ["coldbox@6", "coldbox@7"]
        include:
          - cfengine: "lucee@be"
            experimental: true
            coldbox: "coldbox@7"
          - cfengine: "adobe@be"
            experimental: true
            coldbox: "coldbox@7"
          - cfengine: "boxlang@be"
            experimental: true
            coldbox: "coldbox@7"
          - cfengine: "boxlang-cfml@be"
            experimental: true
            coldbox: "coldbox@7"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.2.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Install CommandBox-BoxLang
        run: box install commandbox-boxlang

      - name: Install dependencies
        run: |
          box install
          box install ${{ matrix.coldbox }} --noSave

      - name: Start server
        run: |
          box server start serverConfigFile="server-${{ matrix.cfengine }}.json" --noSaveSettings --debug
          curl http://127.0.0.1:60299

      - name: Run TestBox Tests
        continue-on-error: ${{ matrix.experimental }}
        run: box testbox run